import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Header from "../components/header";
import Link from "next/link";

export default function Home() {
  return (
    <div className="font-sans">
      <Head>
        <title>Save Space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"/>
      </Head>

      <Header />

      <HeroSection />

    </div>
  )
}

function HeroSection () {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6">
      <div className="flex items-center space-x-14 py-14">
        <div className="w-1/2">
          <div>
            <h1 className="text-4.5xl font-bold text-slate-900">
              <span className="block">
                You Don’t Save, {' '}
                <span className="before:block before:absolute before:-inset-1 before:bg-brand-500 custom-skew relative inline-block">
                  <span className="relative text-white">We Save!</span>
                </span>
              </span>
              <span className="block mt-2">Your Money, Your Terms.</span>
            </h1>
            <p className="mt-4 text-brand-gray text-lg leading-7">
              Disrupting the traditional financial sector by offering better financial solutions,
              while staying true to the human values of trust,
              honesty, and fairness. Secure your future with our secure investments.
            </p>
            <Link href="/">
              <a className="inline-flex mt-6 w-auto items-center py-4 px-6 bg-brand-500 text-white font-bold text-lg rounded-lg hover:bg-blue-700">Create Free Account</a>
            </Link>
          </div>
          <div className="mt-12 flex items-center space-x-4">
            <Link href="/">
              <a className="inline-flex items-center py-4 px-6 border border-brand-500 bg-transparent text-lg font-bold text-brand-500 rounded-lg hover:bg-blue-50">
                <svg className="h-6 w-6 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                  <path d="M17.517 12.556c-.01-1.599.715-2.804 2.178-3.692-.818-1.172-2.056-1.816-3.687-1.94-1.545-.122-3.235.9-3.853.9-.654 0-2.15-.858-3.326-.858C6.4 7.003 3.82 8.902 3.82 12.764c0 1.142.209 2.32.626 3.534.558 1.599 2.569 5.515 4.667 5.452 1.096-.026 1.872-.778 3.3-.778 1.385 0 2.102.778 3.325.778 2.117-.03 3.935-3.59 4.465-5.194-2.838-1.338-2.686-3.919-2.686-4Zm-2.463-7.149c1.188-1.41 1.08-2.695 1.045-3.157-1.05.06-2.264.715-2.955 1.519-.762.862-1.21 1.929-1.114 3.131 1.135.087 2.17-.497 3.024-1.493Z" fill="#1E1E1E"/>
                </svg>
                Get On Apple
              </a>
            </Link>
            <Link href="/">
              <a className="inline-flex items-center py-4 px-6 border border-brand-500 bg-transparent text-lg font-bold text-brand-500 rounded-lg hover:bg-blue-50">
                <svg className="h-6 w-6 mr-2" fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                  <g clipPath="url(#a)">
                    <path d="M18.423 8.232C15.635 6.672 11.16 4.17 4.22.282A1.673 1.673 0 0 0 2.748.09L14.656 12l3.767-3.767Z" fill="#32BBFF"/>
                    <path d="M2.748.09a1.675 1.675 0 0 0-1.144 1.597V22.31a1.674 1.674 0 0 0 1.144 1.598l11.908-11.91L2.748.09ZM14.657 11.999 2.748 23.908a1.656 1.656 0 0 0 1.472-.193c6.731-3.769 11.155-6.243 13.976-7.816l.231-.13-3.77-3.77Z" fill="#32BBFF"/>
                    <path d="M1.604 11.999v10.312a1.674 1.674 0 0 0 1.144 1.597l11.908-11.909H1.604Z" fill="#2C9FD9"/>
                    <path d="M4.22.283A1.679 1.679 0 0 0 2.495.199l11.981 11.98 3.947-3.947C15.637 6.673 11.162 4.17 4.22.282Z" fill="#29CC5E"/>
                    <path d="m14.476 11.819-11.98 11.98a1.667 1.667 0 0 0 1.724-.083 9959.34 9959.34 0 0 1 13.976-7.817l.231-.13-3.95-3.95Z" fill="#D93F21"/>
                    <path d="M23.397 11.999a1.67 1.67 0 0 0-.86-1.468s-1.069-.596-4.345-2.428l-3.896 3.896 3.9 3.9c3.24-1.819 4.34-2.432 4.34-2.432.572-.32.86-.897.86-1.468Z" fill="#FFD500"/>
                    <path d="M22.537 13.467c.571-.32.86-.897.86-1.468h-9.101l3.9 3.9c3.24-1.819 4.34-2.432 4.34-2.432Z" fill="#FA0"/>
                  </g>
                  <defs>
                    <clipPath id="a"><path fill="#fff" transform="translate(.5)" d="M0 0h24v24H0z"/></clipPath>
                  </defs>
                </svg>
                Get On Android
              </a>
            </Link>
          </div>
        </div>
        <div className="w-1/2">
          <div className="relative">
            <img className="h-[656px] w-auto object-cover" src="/girl-smiling.png" alt="Girl Smiling"/>
            <div className="absolute left-0 bottom-0 z-[-1] h-[523px] w-[478px] bg-brand-500 rounded-xl" />
            <div className="absolute right-0 bottom-[52px] w-[438px] h-[424px] bg-brand-700 rounded-xl z-[-2]"></div>
          </div>
        </div>
      </div>
    </div>
  )
}
